version: "3"

services:
  nginx:
    image: registry:5000/gngsn/nginx-nuxt:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    depends_on:
      - web
    environment:
      SERVICE_PORTS: 80   # ðŸ“Œ
      WORKER_PROCESSES: 2
      WORKER_CONNECTIONS: 1024
      KEEPALIVE_TIMEOUT: 65
      GZIP: "on"
      BACKEND_HOST: todo_app_api:3000   # ðŸ“Œ
      BACKEND_MAX_FAILS: 3
      BACKEND_FAIL_TIMEOUT: 10s
      SERVER_PORT: 80
      SERVER_NAME: todo_app_nginx
      LOG_STDOUT: "true"
    networks:
      - todoapp
    volumes:
      - assets:/var/www/_nuxt   # ðŸ“Œ

  web:
    image: registry:5000/gngsn/todoweb:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role != manager]
    environment:
      TODO_API_URL: http://todo_app_nginx   # ðŸ“Œ
    networks:
      - todoapp
    volumes:
      - assets:/todoweb/.nuxt/dist   # ðŸ“Œ

networks:
  todoapp:
    external: true

volumes:  # ðŸ“Œ
  assets:
    driver: local